export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          name: string;
          email: string;
          avatar_url: string | null;
          role: 'user' | 'admin';
          company: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name?: string;
          email: string;
          avatar_url?: string | null;
          role?: 'user' | 'admin';
          company?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          avatar_url?: string | null;
          role?: 'user' | 'admin';
          company?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      workflows: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string;
          long_description: string | null;
          category: string;
          difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
          runtime: string;
          downloads: number;
          rating: number;
          reviews: number;
          tags: string[];
          pricing: 'Free' | 'Premium';
          steps: Json;
          env_vars: Json;
          integrations: string[];
          patch_notes: Json;
          tier: 'Free' | 'Professional' | 'Enterprise';
          current_version: string;
          setup_guide: string | null;
          success_rate: number;
          total_executions: number;
          featured: boolean;
          thumbnail: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description: string;
          long_description?: string | null;
          category: string;
          difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
          runtime?: string;
          downloads?: number;
          rating?: number;
          reviews?: number;
          tags?: string[];
          pricing?: 'Free' | 'Premium';
          steps?: Json;
          env_vars?: Json;
          integrations?: string[];
          patch_notes?: Json;
          tier?: 'Free' | 'Professional' | 'Enterprise';
          current_version?: string;
          setup_guide?: string | null;
          success_rate?: number;
          total_executions?: number;
          featured?: boolean;
          thumbnail?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string;
          long_description?: string | null;
          category?: string;
          difficulty?: 'Beginner' | 'Intermediate' | 'Advanced';
          runtime?: string;
          downloads?: number;
          rating?: number;
          reviews?: number;
          tags?: string[];
          pricing?: 'Free' | 'Premium';
          steps?: Json;
          env_vars?: Json;
          integrations?: string[];
          patch_notes?: Json;
          tier?: 'Free' | 'Professional' | 'Enterprise';
          current_version?: string;
          setup_guide?: string | null;
          success_rate?: number;
          total_executions?: number;
          featured?: boolean;
          thumbnail?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      agents: {
        Row: {
          id: string;
          name: string;
          slug: string;
          type: 'SDR' | 'Support' | 'Operations';
          description: string;
          features: string[];
          status: 'Popular' | 'New' | 'Featured';
          deployment: 'Managed' | 'Self-hosted' | 'Hybrid';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          type: 'SDR' | 'Support' | 'Operations';
          description: string;
          features?: string[];
          status?: 'Popular' | 'New' | 'Featured';
          deployment?: 'Managed' | 'Self-hosted' | 'Hybrid';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          type?: 'SDR' | 'Support' | 'Operations';
          description?: string;
          features?: string[];
          status?: 'Popular' | 'New' | 'Featured';
          deployment?: 'Managed' | 'Self-hosted' | 'Hybrid';
          created_at?: string;
          updated_at?: string;
        };
      };
      assets: {
        Row: {
          id: string;
          name: string;
          slug: string;
          type: 'Prompt Pack' | 'Dataset' | 'Playbook' | 'Creative Bundle';
          description: string;
          category: string;
          downloads: number;
          rating: number;
          pricing: 'Free' | 'Premium';
          file_size: string | null;
          format: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          type: 'Prompt Pack' | 'Dataset' | 'Playbook' | 'Creative Bundle';
          description: string;
          category: string;
          downloads?: number;
          rating?: number;
          pricing?: 'Free' | 'Premium';
          file_size?: string | null;
          format?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          type?: 'Prompt Pack' | 'Dataset' | 'Playbook' | 'Creative Bundle';
          description?: string;
          category?: string;
          downloads?: number;
          rating?: number;
          pricing?: 'Free' | 'Premium';
          file_size?: string | null;
          format?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          long_description: string | null;
          product_type: 'workflow' | 'agent' | 'asset' | 'service' | 'tool';
          category_id: string | null;
          pricing_model: 'free' | 'one_time' | 'subscription' | 'usage_based' | 'custom';
          base_price: number;
          currency: string;
          minimum_tier: 'free' | 'starter' | 'professional' | 'enterprise';
          features: Json;
          specifications: Json;
          media: Json;
          deployment_model: 'managed' | 'self_hosted' | 'hybrid' | 'download' | 'saas' | null;
          integrations: string[];
          tags: string[];
          difficulty_level: 'beginner' | 'intermediate' | 'advanced' | 'expert' | null;
          setup_time_minutes: number | null;
          is_featured: boolean;
          is_active: boolean;
          install_count: number;
          view_count: number;
          average_rating: number;
          review_count: number;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          long_description?: string | null;
          product_type: 'workflow' | 'agent' | 'asset' | 'service' | 'tool';
          category_id?: string | null;
          pricing_model: 'free' | 'one_time' | 'subscription' | 'usage_based' | 'custom';
          base_price?: number;
          currency?: string;
          minimum_tier?: 'free' | 'starter' | 'professional' | 'enterprise';
          features?: Json;
          specifications?: Json;
          media?: Json;
          deployment_model?: 'managed' | 'self_hosted' | 'hybrid' | 'download' | 'saas' | null;
          integrations?: string[];
          tags?: string[];
          difficulty_level?: 'beginner' | 'intermediate' | 'advanced' | 'expert' | null;
          setup_time_minutes?: number | null;
          is_featured?: boolean;
          is_active?: boolean;
          install_count?: number;
          view_count?: number;
          average_rating?: number;
          review_count?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          long_description?: string | null;
          product_type?: 'workflow' | 'agent' | 'asset' | 'service' | 'tool';
          category_id?: string | null;
          pricing_model?: 'free' | 'one_time' | 'subscription' | 'usage_based' | 'custom';
          base_price?: number;
          currency?: string;
          minimum_tier?: 'free' | 'starter' | 'professional' | 'enterprise';
          features?: Json;
          specifications?: Json;
          media?: Json;
          deployment_model?: 'managed' | 'self_hosted' | 'hybrid' | 'download' | 'saas' | null;
          integrations?: string[];
          tags?: string[];
          difficulty_level?: 'beginner' | 'intermediate' | 'advanced' | 'expert' | null;
          setup_time_minutes?: number | null;
          is_featured?: boolean;
          is_active?: boolean;
          install_count?: number;
          view_count?: number;
          average_rating?: number;
          review_count?: number;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      product_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          parent_id: string | null;
          icon: string | null;
          display_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          parent_id?: string | null;
          icon?: string | null;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          parent_id?: string | null;
          icon?: string | null;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      pricing_tiers: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          price_monthly: number;
          price_annual: number;
          features: Json;
          limits: Json;
          display_order: number;
          is_active: boolean;
          is_custom: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          price_monthly?: number;
          price_annual?: number;
          features?: Json;
          limits?: Json;
          display_order?: number;
          is_active?: boolean;
          is_custom?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          price_monthly?: number;
          price_annual?: number;
          features?: Json;
          limits?: Json;
          display_order?: number;
          is_active?: boolean;
          is_custom?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          tier_id: string;
          status: 'active' | 'trialing' | 'past_due' | 'canceled' | 'paused';
          billing_cycle: 'monthly' | 'annual';
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end: boolean;
          canceled_at: string | null;
          stripe_subscription_id: string | null;
          stripe_customer_id: string | null;
          trial_ends_at: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          tier_id: string;
          status?: 'active' | 'trialing' | 'past_due' | 'canceled' | 'paused';
          billing_cycle?: 'monthly' | 'annual';
          current_period_start?: string;
          current_period_end: string;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          trial_ends_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          tier_id?: string;
          status?: 'active' | 'trialing' | 'past_due' | 'canceled' | 'paused';
          billing_cycle?: 'monthly' | 'annual';
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          canceled_at?: string | null;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          trial_ends_at?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          user_id: string;
          order_number: string;
          status: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
          subtotal: number;
          tax: number;
          discount: number;
          total: number;
          currency: string;
          payment_method: string | null;
          stripe_payment_intent_id: string | null;
          stripe_charge_id: string | null;
          invoice_url: string | null;
          receipt_url: string | null;
          billing_details: Json;
          metadata: Json;
          paid_at: string | null;
          refunded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          order_number: string;
          status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
          subtotal?: number;
          tax?: number;
          discount?: number;
          total?: number;
          currency?: string;
          payment_method?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          invoice_url?: string | null;
          receipt_url?: string | null;
          billing_details?: Json;
          metadata?: Json;
          paid_at?: string | null;
          refunded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          order_number?: string;
          status?: 'pending' | 'processing' | 'completed' | 'failed' | 'refunded';
          subtotal?: number;
          tax?: number;
          discount?: number;
          total?: number;
          currency?: string;
          payment_method?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          invoice_url?: string | null;
          receipt_url?: string | null;
          billing_details?: Json;
          metadata?: Json;
          paid_at?: string | null;
          refunded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_workflows: {
        Row: {
          id: string;
          user_id: string;
          workflow_id: string;
          status: 'deployed' | 'paused' | 'draft';
          config: Json;
          last_run: string | null;
          runs_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          workflow_id: string;
          status?: 'deployed' | 'paused' | 'draft';
          config?: Json;
          last_run?: string | null;
          runs_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          workflow_id?: string;
          status?: 'deployed' | 'paused' | 'draft';
          config?: Json;
          last_run?: string | null;
          runs_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      workflow_executions: {
        Row: {
          id: string;
          user_workflow_id: string;
          status: 'running' | 'completed' | 'failed';
          started_at: string;
          completed_at: string | null;
          duration_ms: number | null;
          error_message: string | null;
          output: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_workflow_id: string;
          status?: 'running' | 'completed' | 'failed';
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
          error_message?: string | null;
          output?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_workflow_id?: string;
          status?: 'running' | 'completed' | 'failed';
          started_at?: string;
          completed_at?: string | null;
          duration_ms?: number | null;
          error_message?: string | null;
          output?: Json | null;
          created_at?: string;
        };
      };
      affiliates: {
        Row: {
          id: string;
          user_id: string | null;
          affiliate_code: string;
          status: 'pending' | 'approved' | 'suspended' | 'terminated';
          tier: 'standard' | 'silver' | 'gold' | 'platinum';
          company_name: string | null;
          website_url: string | null;
          promotional_methods: string[];
          audience_size: number | null;
          application_notes: string | null;
          approved_at: string | null;
          approved_by: string | null;
          suspension_reason: string | null;
          total_clicks: number;
          total_conversions: number;
          total_revenue_cents: number;
          total_commissions_cents: number;
          total_paid_cents: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          affiliate_code: string;
          status?: 'pending' | 'approved' | 'suspended' | 'terminated';
          tier?: 'standard' | 'silver' | 'gold' | 'platinum';
          company_name?: string | null;
          website_url?: string | null;
          promotional_methods?: string[];
          audience_size?: number | null;
          application_notes?: string | null;
          approved_at?: string | null;
          approved_by?: string | null;
          suspension_reason?: string | null;
          total_clicks?: number;
          total_conversions?: number;
          total_revenue_cents?: number;
          total_commissions_cents?: number;
          total_paid_cents?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          affiliate_code?: string;
          status?: 'pending' | 'approved' | 'suspended' | 'terminated';
          tier?: 'standard' | 'silver' | 'gold' | 'platinum';
          company_name?: string | null;
          website_url?: string | null;
          promotional_methods?: string[];
          audience_size?: number | null;
          application_notes?: string | null;
          approved_at?: string | null;
          approved_by?: string | null;
          suspension_reason?: string | null;
          total_clicks?: number;
          total_conversions?: number;
          total_revenue_cents?: number;
          total_commissions_cents?: number;
          total_paid_cents?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      professional_tools: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          category: string;
          tool_type: string;
          features: Json;
          templates_count: number;
          pricing_tier: string;
          free_uses_per_month: number;
          is_active: boolean;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          description: string;
          category?: string;
          tool_type: string;
          features?: Json;
          templates_count?: number;
          pricing_tier?: string;
          free_uses_per_month?: number;
          is_active?: boolean;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          description?: string;
          category?: string;
          tool_type?: string;
          features?: Json;
          templates_count?: number;
          pricing_tier?: string;
          free_uses_per_month?: number;
          is_active?: boolean;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      tool_usage: {
        Row: {
          id: string;
          user_id: string | null;
          tool_id: string;
          usage_type: string;
          usage_data: Json;
          result_data: Json;
          session_id: string | null;
          ip_address: string | null;
          user_agent: string | null;
          duration_ms: number | null;
          success: boolean;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          tool_id: string;
          usage_type?: string;
          usage_data?: Json;
          result_data?: Json;
          session_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          duration_ms?: number | null;
          success?: boolean;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          tool_id?: string;
          usage_type?: string;
          usage_data?: Json;
          result_data?: Json;
          session_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          duration_ms?: number | null;
          success?: boolean;
          error_message?: string | null;
          created_at?: string;
        };
      };
      tool_templates: {
        Row: {
          id: string;
          tool_id: string;
          name: string;
          description: string | null;
          category: string | null;
          industry: string | null;
          template_data: Json;
          preview_image: string | null;
          is_premium: boolean;
          usage_count: number;
          rating: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          tool_id: string;
          name: string;
          description?: string | null;
          category?: string | null;
          industry?: string | null;
          template_data?: Json;
          preview_image?: string | null;
          is_premium?: boolean;
          usage_count?: number;
          rating?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          tool_id?: string;
          name?: string;
          description?: string | null;
          category?: string | null;
          industry?: string | null;
          template_data?: Json;
          preview_image?: string | null;
          is_premium?: boolean;
          usage_count?: number;
          rating?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      user_tool_creations: {
        Row: {
          id: string;
          user_id: string;
          tool_id: string;
          template_id: string | null;
          name: string;
          content: Json;
          status: string;
          version: number;
          share_token: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          tool_id: string;
          template_id?: string | null;
          name: string;
          content?: Json;
          status?: string;
          version?: number;
          share_token?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          tool_id?: string;
          template_id?: string | null;
          name?: string;
          content?: Json;
          status?: string;
          version?: number;
          share_token?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      tool_usage_limits: {
        Row: {
          id: string;
          user_id: string;
          tool_id: string;
          period_start: string;
          period_end: string;
          usage_count: number;
          limit_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          tool_id: string;
          period_start: string;
          period_end: string;
          usage_count?: number;
          limit_count: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          tool_id?: string;
          period_start?: string;
          period_end?: string;
          usage_count?: number;
          limit_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
